version: "3"
services:
 db:
  image: postgres
  ports:
  - 5432:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: root
   POSTGRES_DB: ValorDolar

  volumes:
  - ./migrations:/docker-entrypoint-initdb.d/* 
 app: 
  image: dolar-quot-server
  ports: 
   - 3000:3000