version: "3.9"
services:
 db:
  image: postgres
  restart: always
  ports:
  - 5431:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_HOST: postgres
   POSTGRES_PASSWORD: root
   POSTGRES_DB: ValorDolar

  volumes:
  - ./migrations:/docker-entrypoint-initdb.d/
 app:
  depends_on:
      - db
  image: dolar-quot-server
  ports: 
   - 3000:3000